//name : ChangeEndianness
//input : input_big_endian:16
//output : output_little_endian:16
//source_file : /home/wsluser/ChangeEndianness.c

///+============================================================================+
///|                                                                            |
///|                     This file was generated by Chips                       |
///|                                                                            |
///|                                  Chips                                     |
///|                                                                            |
///|                      http://github.com/dawsonjon/Chips-2.0                 |
///|                                                                            |
///|                                                             Python powered |
///+============================================================================+
module ChangeEndianness(input_big_endian,input_big_endian_stb,output_little_endian_ack,clk,rst,output_little_endian,output_little_endian_stb,input_big_endian_ack,exception);
  integer file_count;
  parameter  stop = 3'd0,
  instruction_fetch = 3'd1,
  operand_fetch = 3'd2,
  execute = 3'd3,
  load = 3'd4,
  wait_state = 3'd5,
  read = 3'd6,
  write = 3'd7;
  input [31:0] input_big_endian;
  input input_big_endian_stb;
  input output_little_endian_ack;
  input clk;
  input rst;
  output [31:0] output_little_endian;
  output output_little_endian_stb;
  output input_big_endian_ack;
  reg [31:0] timer;
  reg [63:0] timer_clock;
  reg [15:0] program_counter;
  reg [15:0] program_counter_1;
  reg [15:0] program_counter_2;
  reg [43:0] instruction;
  reg [3:0] opcode_2;
  reg [3:0] a;
  reg [3:0] b;
  reg [3:0] z;
  reg write_enable;
  reg [3:0] address_a_2;
  reg [3:0] address_b_2;
  reg [3:0] address_z_2;
  reg [3:0] address_z_3;
  reg [31:0] load_data;
  reg [31:0] write_output;
  reg [31:0] write_value;
  reg [31:0] read_input;
  reg [15:0] literal_2;
  reg [31:0] a_hi;
  reg [31:0] b_hi;
  reg [31:0] a_lo;
  reg [31:0] b_lo;
  reg [63:0] long_result;
  reg [31:0] result;
  reg [15:0] address;
  reg [31:0] data_out;
  reg [31:0] data_in;
  reg [31:0] carry;
  reg [31:0] s_output_little_endian_stb;
  reg [31:0] s_output_little_endian;
  reg [31:0] s_input_big_endian_ack;
  reg [7:0] state;
  output reg exception;
  reg [27:0] instructions [88:0];
  reg [31:0] memory [4095:0];
  reg [31:0] registers [15:0];
  wire [31:0] operand_a;
  wire [31:0] operand_b;
  wire [31:0] register_a;
  wire [31:0] register_b;
  wire [15:0] literal;
  wire [3:0] opcode;
  wire [3:0] address_a;
  wire [3:0] address_b;
  wire [3:0] address_z;
  wire [15:0] load_address;
  wire [15:0] store_address;
  wire [31:0] store_data;
  wire  store_enable;
  wire  forward_a;
  wire  forward_b;

  //////////////////////////////////////////////////////////////////////////////
  // MEMORY INITIALIZATION                                                      
  //                                                                            
  // In order to reduce program size, array contents have been stored into      
  // memory at initialization. In an FPGA, this will result in the memory being 
  // initialized when the FPGA configures.                                      
  // Memory will not be re-initialized at reset.                                
  // Dissable this behaviour using the no_initialize_memory switch              
  
  initial
  begin
  end


  //////////////////////////////////////////////////////////////////////////////
  // INSTRUCTION INITIALIZATION                                                 
  //                                                                            
  // Initialise the contents of the instruction memory                          
  //
  // Intruction Set
  // ==============
  // 0 {'op': 'literal', 'literal': True}
  // 1 {'op': 'addl', 'literal': True}
  // 2 {'op': 'store', 'literal': False}
  // 3 {'op': 'call', 'literal': True}
  // 4 {'op': 'stop', 'literal': False}
  // 5 {'op': 'load', 'literal': False}
  // 6 {'op': 'unsigned_greater', 'literal': False}
  // 7 {'op': 'jmp_if_false', 'literal': True}
  // 8 {'op': 'read', 'literal': False}
  // 9 {'op': 'write', 'literal': False}
  // 10 {'op': 'add', 'literal': False}
  // 11 {'op': 'goto', 'literal': True}
  // 12 {'op': 'return', 'literal': False}
  // Intructions
  // ===========
  
  initial
  begin
    instructions[0] = {4'd0, 4'd3, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'literal', 'z': 3, 'literal': 0}
    instructions[1] = {4'd0, 4'd4, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'literal', 'z': 4, 'literal': 0}
    instructions[2] = {4'd1, 4'd3, 4'd3, 16'd3};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 3}
    instructions[3] = {4'd0, 4'd8, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 8 {'trace': /home/wsluser/ChangeEndianness.c : 8, 'op': 'literal', 'z': 8, 'literal': 0}
    instructions[4] = {4'd0, 4'd2, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 8 {'trace': /home/wsluser/ChangeEndianness.c : 8, 'op': 'literal', 'z': 2, 'literal': 0}
    instructions[5] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 8 {'trace': /home/wsluser/ChangeEndianness.c : 8, 'op': 'store', 'b': 8, 'a': 2}
    instructions[6] = {4'd0, 4'd8, 4'd0, 16'd1};///home/wsluser/ChangeEndianness.c : 9 {'trace': /home/wsluser/ChangeEndianness.c : 9, 'op': 'literal', 'z': 8, 'literal': 1}
    instructions[7] = {4'd0, 4'd2, 4'd0, 16'd1};///home/wsluser/ChangeEndianness.c : 9 {'trace': /home/wsluser/ChangeEndianness.c : 9, 'op': 'literal', 'z': 2, 'literal': 1}
    instructions[8] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 9 {'trace': /home/wsluser/ChangeEndianness.c : 9, 'op': 'store', 'b': 8, 'a': 2}
    instructions[9] = {4'd0, 4'd8, 4'd0, 16'd128};///home/wsluser/ChangeEndianness.c : 6 {'trace': /home/wsluser/ChangeEndianness.c : 6, 'op': 'literal', 'z': 8, 'literal': 128}
    instructions[10] = {4'd0, 4'd2, 4'd0, 16'd2};///home/wsluser/ChangeEndianness.c : 6 {'trace': /home/wsluser/ChangeEndianness.c : 6, 'op': 'literal', 'z': 2, 'literal': 2}
    instructions[11] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 6 {'trace': /home/wsluser/ChangeEndianness.c : 6, 'op': 'store', 'b': 8, 'a': 2}
    instructions[12] = {4'd1, 4'd7, 4'd4, 16'd0};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'addl', 'z': 7, 'a': 4, 'literal': 0}
    instructions[13] = {4'd1, 4'd4, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'addl', 'z': 4, 'a': 3, 'literal': 0}
    instructions[14] = {4'd3, 4'd6, 4'd0, 16'd16};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'call', 'z': 6, 'label': 16}
    instructions[15] = {4'd4, 4'd0, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 27 {'trace': /home/wsluser/ChangeEndianness.c : 27, 'op': 'stop'}
    instructions[16] = {4'd1, 4'd3, 4'd3, 16'd4};///home/wsluser/ChangeEndianness.c : 11 {'trace': /home/wsluser/ChangeEndianness.c : 11, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 4}
    instructions[17] = {4'd0, 4'd8, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'literal', 'z': 8, 'literal': 0}
    instructions[18] = {4'd1, 4'd2, 4'd4, 16'd2};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 2, 'a': 4, 'literal': 2}
    instructions[19] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'store', 'b': 8, 'a': 2}
    instructions[20] = {4'd1, 4'd8, 4'd4, 16'd2};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 8, 'a': 4, 'literal': 2}
    instructions[21] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[22] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 8, 'a': 2}
    instructions[23] = {4'd2, 4'd0, 4'd3, 16'd8};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'store', 'a': 3, 'b': 8, 'comment': 'push'}
    instructions[24] = {4'd1, 4'd3, 4'd3, 16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 1}
    instructions[25] = {4'd0, 4'd8, 4'd0, 16'd64};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'literal', 'z': 8, 'literal': 64}
    instructions[26] = {4'd1, 4'd3, 4'd3, -16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': -1, 'comment': 'pop'}
    instructions[27] = {4'd5, 4'd10, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 10, 'a': 3}
    instructions[28] = {4'd6, 4'd8, 4'd8, 16'd10};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'unsigned_greater', 'z': 8, 'a': 8, 'b': 10}
    instructions[29] = {4'd7, 4'd0, 4'd8, 16'd85};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'jmp_if_false', 'a': 8, 'label': 85}
    instructions[30] = {4'd0, 4'd8, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'literal', 'z': 8, 'literal': 0}
    instructions[31] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[32] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'load', 'z': 8, 'a': 2}
    instructions[33] = {4'd8, 4'd8, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'read', 'z': 8, 'a': 8}
    instructions[34] = {4'd1, 4'd2, 4'd4, 16'd0};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'addl', 'z': 2, 'a': 4, 'literal': 0}
    instructions[35] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 20 {'trace': /home/wsluser/ChangeEndianness.c : 20, 'op': 'store', 'b': 8, 'a': 2}
    instructions[36] = {4'd0, 4'd8, 4'd0, 16'd0};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'literal', 'z': 8, 'literal': 0}
    instructions[37] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[38] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'load', 'z': 8, 'a': 2}
    instructions[39] = {4'd8, 4'd8, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'read', 'z': 8, 'a': 8}
    instructions[40] = {4'd1, 4'd2, 4'd4, 16'd1};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'addl', 'z': 2, 'a': 4, 'literal': 1}
    instructions[41] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 21 {'trace': /home/wsluser/ChangeEndianness.c : 21, 'op': 'store', 'b': 8, 'a': 2}
    instructions[42] = {4'd0, 4'd8, 4'd0, 16'd1};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'literal', 'z': 8, 'literal': 1}
    instructions[43] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[44] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'load', 'z': 8, 'a': 2}
    instructions[45] = {4'd2, 4'd0, 4'd3, 16'd8};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'store', 'a': 3, 'b': 8, 'comment': 'push'}
    instructions[46] = {4'd1, 4'd3, 4'd3, 16'd1};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 1}
    instructions[47] = {4'd1, 4'd8, 4'd4, 16'd1};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 8, 'a': 4, 'literal': 1}
    instructions[48] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[49] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'load', 'z': 8, 'a': 2}
    instructions[50] = {4'd1, 4'd3, 4'd3, -16'd1};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 3, 'a': 3, 'literal': -1, 'comment': 'pop'}
    instructions[51] = {4'd5, 4'd0, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'load', 'z': 0, 'a': 3}
    instructions[52] = {4'd9, 4'd0, 4'd0, 16'd8};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'write', 'a': 0, 'b': 8}
    instructions[53] = {4'd1, 4'd3, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 22 {'trace': /home/wsluser/ChangeEndianness.c : 22, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 0}
    instructions[54] = {4'd0, 4'd8, 4'd0, 16'd1};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'literal', 'z': 8, 'literal': 1}
    instructions[55] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[56] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'load', 'z': 8, 'a': 2}
    instructions[57] = {4'd2, 4'd0, 4'd3, 16'd8};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'store', 'a': 3, 'b': 8, 'comment': 'push'}
    instructions[58] = {4'd1, 4'd3, 4'd3, 16'd1};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 1}
    instructions[59] = {4'd1, 4'd8, 4'd4, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 8, 'a': 4, 'literal': 0}
    instructions[60] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[61] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'load', 'z': 8, 'a': 2}
    instructions[62] = {4'd1, 4'd3, 4'd3, -16'd1};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 3, 'a': 3, 'literal': -1, 'comment': 'pop'}
    instructions[63] = {4'd5, 4'd0, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'load', 'z': 0, 'a': 3}
    instructions[64] = {4'd9, 4'd0, 4'd0, 16'd8};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'write', 'a': 0, 'b': 8}
    instructions[65] = {4'd1, 4'd3, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 23 {'trace': /home/wsluser/ChangeEndianness.c : 23, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 0}
    instructions[66] = {4'd1, 4'd8, 4'd4, 16'd2};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 8, 'a': 4, 'literal': 2}
    instructions[67] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[68] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 8, 'a': 2}
    instructions[69] = {4'd2, 4'd0, 4'd3, 16'd8};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'store', 'a': 3, 'b': 8, 'comment': 'push'}
    instructions[70] = {4'd1, 4'd3, 4'd3, 16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 1}
    instructions[71] = {4'd0, 4'd8, 4'd0, 16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'literal', 'z': 8, 'literal': 1}
    instructions[72] = {4'd2, 4'd0, 4'd3, 16'd8};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'store', 'a': 3, 'b': 8, 'comment': 'push'}
    instructions[73] = {4'd1, 4'd3, 4'd3, 16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': 1}
    instructions[74] = {4'd1, 4'd8, 4'd4, 16'd2};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 8, 'a': 4, 'literal': 2}
    instructions[75] = {4'd1, 4'd2, 4'd8, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 2, 'a': 8, 'literal': 0}
    instructions[76] = {4'd5, 4'd8, 4'd2, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 8, 'a': 2}
    instructions[77] = {4'd1, 4'd3, 4'd3, -16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': -1, 'comment': 'pop'}
    instructions[78] = {4'd5, 4'd10, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 10, 'a': 3}
    instructions[79] = {4'd10, 4'd8, 4'd8, 16'd10};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'add', 'z': 8, 'a': 8, 'b': 10}
    instructions[80] = {4'd1, 4'd2, 4'd4, 16'd2};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 2, 'a': 4, 'literal': 2}
    instructions[81] = {4'd2, 4'd0, 4'd2, 16'd8};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'store', 'b': 8, 'a': 2}
    instructions[82] = {4'd1, 4'd3, 4'd3, -16'd1};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'addl', 'z': 3, 'a': 3, 'literal': -1, 'comment': 'pop'}
    instructions[83] = {4'd5, 4'd8, 4'd3, 16'd0};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'load', 'z': 8, 'a': 3}
    instructions[84] = {4'd11, 4'd0, 4'd0, 16'd20};///home/wsluser/ChangeEndianness.c : 19 {'trace': /home/wsluser/ChangeEndianness.c : 19, 'op': 'goto', 'label': 20}
    instructions[85] = {4'd11, 4'd0, 4'd0, 16'd17};///home/wsluser/ChangeEndianness.c : 18 {'trace': /home/wsluser/ChangeEndianness.c : 18, 'op': 'goto', 'label': 17}
    instructions[86] = {4'd1, 4'd3, 4'd4, 16'd0};///home/wsluser/ChangeEndianness.c : 11 {'trace': /home/wsluser/ChangeEndianness.c : 11, 'op': 'addl', 'z': 3, 'a': 4, 'literal': 0}
    instructions[87] = {4'd1, 4'd4, 4'd7, 16'd0};///home/wsluser/ChangeEndianness.c : 11 {'trace': /home/wsluser/ChangeEndianness.c : 11, 'op': 'addl', 'z': 4, 'a': 7, 'literal': 0}
    instructions[88] = {4'd12, 4'd0, 4'd6, 16'd0};///home/wsluser/ChangeEndianness.c : 11 {'trace': /home/wsluser/ChangeEndianness.c : 11, 'op': 'return', 'a': 6}
  end

  
  always @(posedge clk)
  begin
    load_data <= memory[load_address];
    if(store_enable && state == execute) begin
      if (store_address > 4095) begin
        $display("!!!!stack overflow!!!!");
        $finish_and_return(1);
        exception <= 1'b1;
      end
      memory[store_address] <= store_data;
    end
    if (rst==1'b1) begin
      exception <= 1'b0;
    end
  end


  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 1 -- FETCH INSTRUCTION
  //                                                                            
  
  always @(posedge clk)
  begin
    //implement memory for instructions
    if (state == instruction_fetch || state == operand_fetch || state == execute) begin
      instruction <= instructions[program_counter];
      program_counter_1 <= program_counter;
    end
  end

  assign opcode    = instruction[27:24];
  assign address_z = instruction[23:20];
  assign address_a = instruction[19:16];
  assign address_b = instruction[3:0];
  assign literal   = instruction[15:0];
  assign forward_a = (address_a_2 == address_z_3 && write_enable);
  assign forward_b = (address_b_2 == address_z_3 && write_enable);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 2 -- FETCH OPERANDS
  //                                                                            
  
  always @(posedge clk)
  begin
    if (write_enable) begin
      registers[address_z_3] <= result;
    end
    if (state == operand_fetch || state == execute) begin
      opcode_2 <= opcode;
      literal_2 <= literal;
      address_a_2 <= address_a;
      address_b_2 <= address_b;
      address_z_2 <= address_z;
      program_counter_2 <= program_counter_1;
    end
  end
  assign register_a = registers[address_a_2];
  assign register_b = registers[address_b_2];
  assign operand_a = forward_a?result:register_a;
  assign operand_b = forward_b?result:register_b;
  assign store_address = operand_a;
  assign load_address = operand_a;
  assign store_data = operand_b;
  assign store_enable = (opcode_2==2);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 3 -- EXECUTE
  //                                                                            
  
  always @(posedge clk)
  begin

  write_enable <= 0;
  timer_clock <= timer_clock + 1;
  case(state)

    //instruction_fetch
    instruction_fetch: begin
      program_counter <= program_counter + 1;
      state <= operand_fetch;
    end
    //operand_fetch
    operand_fetch: begin
      program_counter <= program_counter + 1;
      state <= execute;
    end
    //execute
    execute: begin
      program_counter <= program_counter + 1;
      address_z_3 <= address_z_2;
      case(opcode_2)

        //literal
        16'd0:
        begin
          result<=$signed(literal_2);
          write_enable <= 1;
        end

        //addl
        16'd1:
        begin
          result<=operand_a + literal_2;
          write_enable <= 1;
        end

        //store
        16'd2:
        begin
        end

        //call
        16'd3:
        begin
          result <= program_counter_2 + 1;
          write_enable <= 1;
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //stop
        16'd4:
        begin
        state <= stop;
        end

        //load
        16'd5:
        begin
          state <= load;
        end

        //unsigned_greater
        16'd6:
        begin
          result <= $unsigned(operand_a) > $unsigned(operand_b);
          write_enable <= 1;
        end

        //jmp_if_false
        16'd7:
        begin
          if (operand_a == 0) begin
            program_counter <= literal_2;
            state <= instruction_fetch;
          end
        end

        //read
        16'd8:
        begin
          state <= read;
          read_input <= operand_a;
        end

        //write
        16'd9:
        begin
          state <= write;
          write_output <= operand_a;
          write_value <= operand_b;
        end

        //add
        16'd10:
        begin
          long_result = operand_a + operand_b;
          result <= long_result[31:0];
          carry[0] <= long_result[32];
          write_enable <= 1;
        end

        //goto
        16'd11:
        begin
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //return
        16'd12:
        begin
          program_counter <= operand_a;
          state <= instruction_fetch;
        end

      endcase

    end

    read:
    begin
      case(read_input)
      0:
      begin
        s_input_big_endian_ack <= 1;
        if (s_input_big_endian_ack && input_big_endian_stb) begin
          result <= input_big_endian;
          write_enable <= 1;
          s_input_big_endian_ack <= 0;
          state <= execute;
        end
      end
      endcase
    end

    write:
    begin
      case(write_output)
      1:
      begin
        s_output_little_endian_stb <= 1;
        s_output_little_endian <= write_value;
        if (output_little_endian_ack && s_output_little_endian_stb) begin
          s_output_little_endian_stb <= 0;
          state <= execute;
        end
      end
      endcase
    end

    load:
    begin
        result <= load_data;
        write_enable <= 1;
        state <= execute;
    end

    wait_state:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        state <= execute;
      end
    end

    stop:
    begin
    end

    endcase

    if (rst == 1'b1) begin
      timer <= 0;
      timer_clock <= 0;
      program_counter <= 0;
      address_z_3 <= 0;
      result <= 0;
      a = 0;
      b = 0;
      z = 0;
      state <= instruction_fetch;
      s_input_big_endian_ack <= 0;
      s_output_little_endian_stb <= 0;
    end
  end
  assign input_big_endian_ack = s_input_big_endian_ack;
  assign output_little_endian_stb = s_output_little_endian_stb;
  assign output_little_endian = s_output_little_endian;

endmodule
